first_project/first_app/urls.py
from django.conf.urls import url
from first_app import views

# for template tagging
app_name = 'first_app'


urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^other',views.other,name='other'),
    url(r'^signup',views.signup_page,name='signup'),
    url(r'^$', views.users,name='users'),
    url(r'^$',views.form_name_view,name='form_name'),
    url(r'^relative/$',views.relative,name='relative'),
    url(r'^user_login/', views.user_login,name='user_login'),


]

first_project/first_project/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from first_app import views


urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^other/', views.other,name='other'),
    url(r'^signup',views.signup_page,name='signup'),
    url(r'^formpage/',views.form_name_view,name='form_name'),
    url(r'^relative/',views.relative,name='relative'),
    url(r'^users/', views.users,name='users'),
    url(r'^logout/$', views.user_logout,name='logout'),
    url(r'^special/', views.special,name='special'),
    url(r'^first_app/',include('first_app.urls')),
    url(r'^admin/', admin.site.urls),
]

first_project/first_app/models.py
from django.db import models
from django.contrib.auth.models import User as auth_user

class Topic(models.Model):
    top_name = models.CharField(max_length=264,unique=True)

    def __str__(self):
        return self.top_name

class Webpage(models.Model):
    topic = models.ForeignKey(Topic,on_delete=models.CASCADE)
    name = models.CharField(max_length=264,unique=True)
    url = models.URLField(unique=True)

    def __str__(self):
        return self.name

class AccessRecord(models.Model):
    name = models.ForeignKey(Webpage,on_delete=models.CASCADE)
    date = models.DateField()

    def __str__(self):
        return str(self.date)

class User(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.EmailField(max_length=100,unique=True)

class UserProfileInfo(models.Model):

    user = models.OneToOneField(auth_user,on_delete=models.CASCADE)

    #additional classes
    # blank = true means user does not have to fill this out
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)

    # method for printing this out
    def __str__(self):
        return self.user.username

first_project/first_app/forms.py
from django import forms
from django.core import validators
from first_app.models import User, UserProfileInfo
from django.contrib.auth.models import User as auth_user


# my own validator the name field starts with a Z
# must take in value as parameter
# def check_for_z(value):
#     if value[0].lower() != 'z':
#         raise forms.ValidationError("NAME NEEDS TO START WITH Z")

class FormName(forms.Form):
    name = forms.CharField()#validators=[check_for_z]
    email = forms.EmailField()
    verify_email = forms.EmailField(label='Enter your email again')
    text = forms.CharField(widget=forms.Textarea)
    # false because we dont want to show it on the page for the user
    # can pass in a list of validators
    # botcatcher = forms.CharField(required=False, widget=forms.HiddenInput,validators=[validators.MaxLengthValidator(0)])

    # validating bot input
    # def clean_botcatcher(self):
    #     botcatcher = self.cleaned_data['botcatcher']
    #     if len(botcatcher) > 0:
    #         raise forms.ValidationError("GOTCHA BOT!")
    #     return botcatcher

    # Clean ENTIRE FORM AL AT ONCE instead of individual validator
    def clean(self):
        # returns all clean data for the entire form
        all_clean_data = super().clean()
        email = all_clean_data['email']
        vmail = all_clean_data['verify_email']

        if email != vmail:
            raise forms.ValidationError("MAKE SURE EMAILS MATCH")

class NewUserForm(forms.ModelForm):
    class Meta():
        model = User
        fields = '__all__'


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = auth_user
        fields = ('username','email','password')


class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')

first_project/first_app/views.py
from django.shortcuts import render
from django.http import HttpResponse,HttpResponseRedirect
from first_app.models import Topic,Webpage,AccessRecord
from . import forms
from first_app.forms import NewUserForm,UserProfileInfoForm,UserForm
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate,login,logout

def index(request):
    webpages_list = AccessRecord.objects.order_by('date')
    date_dict = {'access_records': webpages_list}
    return render(request,'first_app/index.html',context=date_dict)

@login_required
def special(request):
        return HttpResponse('YOU ARE LOGING IN! , NICE')


@login_required
def user_logout(request):
        logout(request)
        return HttpResponseRedirect(reverse('index'))


def user_login(request):
        if request.method == 'POST':
                # username is what we called it in the html file
                username = request.POST.get('username')
                password = request.POST.get('password')


                # django built in authentication
                user = authenticate(username=username,password=password)

                if user:
                        if user.is_active:
                                login(request,user)
                                #send user somewhere after log in
                                return HttpResponseRedirect(reverse('index'))
                        else:
                                return HttpResponse('ACCOUNT NOT ACTIVE')
                else:
                        print('Someone tried to log in and failed')
                        print(f"Username: {username} and Password: {password}")
                        return HttpResponse("INVALID LOG IN DETAILS")

        else:
             return render(request,'first_app/login.html',{})   

            

def signup_page(request):
        registered = False

        if request.method =="POST":
                user_form = UserForm(data=request.POST)
                profile_form = UserProfileInfoForm(data=request.POST)

                if user_form.is_valid() and profile_form.is_valid():
                        user = user_form.save()
                        user.set_password(user.password) #hasing password
                        user.save()

                        profile = profile_form.save(commit=False)
                        profile.user = user #sets up ne to one relationship

                        # can also be used to upload a CSV
                        if 'profile_pic' in request.FILES:
                                profile.profile_pic = request.FILES['profile_pic']

                        profile.save()

                        registered=True
                else:
                        print(user_form.errors,profile_form.errors)
        else:
                user_form= UserForm()
                profile_form = UserProfileInfoForm()

        return render(request,'first_app/signup.html',{'user_form':user_form,'profile_form':profile_form,'registered':registered})

def other(request):
    context_dict = {'text':'hello world','number':100}
    return render(request,'first_app/other.html',context_dict)

def relative(request):
        return render(request,'first_app/relative_url_templates.html')

def users(request):
        form = NewUserForm()

        if request.method == 'POST':
                form = NewUserForm(request.POST)
                # to commit to database
                if form.is_valid():
                        form.save(commit=True)
                        return index(request)
                else:
                        print('ERROR FROM INVALID FORM')
        return render(request,'first_app/users.html',{'signup_form':form})

        user_list = User.objects.order_by('first_name')
        user_dict = {'users': user_list}
        return render(request,'first_app/users.html',context=user_dict)

def form_name_view(request):
    form = forms.FormName()

    if request.method == 'POST':
        form = forms.FormName(request.POST)

        if form.is_valid():
            print("VALIDATION SUCCESS!!")
            print("NAME: " + form.cleaned_data['name'])
            print("EMAIL: " + form.cleaned_data['email'])
            print("TEXT: " + form.cleaned_data['text'])


    return render(request,'first_app/form_page.html',{'form':form})

# def signup_page(request):
#         sign_up_form = forms.Signup()

#         return render(request,'first_app/signup.html',{'sign_up_form':sign_up_form})

first_project/templates/first_app/base.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>BASE PAGE</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    </head>
    <body>
       <nav class="navbar navbar-default navbar-static-top">
           <div class="container">
               <ul class="nav navbar-nav">
                   <li><a class="navbar-brand" href="{% url 'index' %}">Brand</a></li>
                   <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
                   <li><a class="navbar-link" href="{% url 'first_app:other' %}">other</a></li>
                   <li><a class="navbar-link" href="{% url 'first_app:signup' %}">Sign Up</a></li>

                    {% if user.is_authenticated %}
                   <li><a class="navbar-link" href="{% url 'logout' %}">Log Out</a></li>
                    {% else %}
                   <li><a class="navbar-link" href="{% url 'first_app:user_login' %}">Log In</a></li>
                    {% endif %}
               </ul>
           </div>
           <div class="container">
            </nav>

            {% block body_block %}
            <!-- anything outside of this will be inherited if you extend -->
            {% endblock %}
           </div>
       
        
        <script src="" async defer></script>
    </body>
</html>

first_project/templates/first_app/form_page.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Form Page</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    </head>
    <body>
        <h1>FILL out the form!</h1>
        <div class="container">
            <form class="" action="" method="POST">
            {{ form.as_p }}
            {% csrf_token %}
            <input type="submit" class="btn btn-primary" value="Submit">
         </form>
        </div>
      
        
        <script src="" async defer></script>
    </body>
</html>

first_project/templates/first_app/index.html
<!DOCTYPE html>
{% extends "first_app/base.html" %}
    {% block body_block %}
        <h1>Welcome to Django level 2!</h1>
        <h2>here are your access records:</h2>

        <div class="djangtwo">
            {% if access_records %}
                <table>
                    <thead>
                        <th>Site Name</th>
                        <th>Date Accessed</th>
                    </thead>
                       <!-- LOGIC LOOPING THROUGH EVERY ROW IN ACCESS RECORDS -->
            {% for acc in access_records %}
            <tr>
                <td>{{ acc.name }}</td>
                <td>{{ acc.date }}</td>
            </tr>
            {% endfor %}
                </table>
                {% else %}
                <p>NO ACCESS RECORDS FOUND!</p>
                {% endif %}

        </div>
        
        <script src="" async defer></script>
     {% endblock %}

first_project/templates/first_app/login.html
{% extends 'first_app/base.html' %}
{% block body_block %}
<div class='jumbotron'>
    <h1>Please Login</h1>
    <form action="{% url 'first_app:user_login' %}" method="POST">
        {%csrf_token%}
        <label for="username">Username:</label>
        <input type="text" name="username"placeholder="Enter Username">
        <label for="password">Password:</label>
        <input type="password" name="password">
        <input type="submit" value="Login">
    </form>

</div>
{% endblock %}

first_project/templates/first_app/other.html
<!DOCTYPE html>
{% extends "first_app/base.html" %}
    {% block body_block %}
<h1>WELCOME TO OTHER!</h1>
<!-- <h2>THis is an example of template inheritance</h2> -->
<!-- filter examples -->
<h1>{{ text|cut:'world'}}</h1>
<h1>{{ number|add:"99" }}</h1>

<!-- CUSTOM FILTERS -->

{% endblock %}

first_project/templates/first_app/relative_url_templates.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>  
        <h1>WELCOME TO RELATIVE TEMPLATES </h1>
        <!-- first_app maches app_name from first_app.urls.py file -->
        <!-- the 'other part is the the name='other' from the urls.py file -->
        <!-- make you to leave NO SPACES AFTER other -->
        <a href="{% url 'first_app:other' %}">The OTHER page</a>
        <!-- calling the admin page it is installed as an app in settings -->
        <a href="{% url 'admin:index' %}">ADMIN PAGE</a>
        <!-- to get to the undex page -->
        <a href="{% url 'index' %}">LINK TO INDEX</a>

        
     
        <script src="" async defer></script>
    </body>
</html>

first_project/templates/first_app/signup.html
<!DOCTYPE html>
{% extends "first_app/base.html" %}
<!-- {% load staticfiles %} if i had any --> 
    {% block body_block %}
    <div class="jumbotron">
        {% if registered %}
            <h1>Thank you for registering</h1>
        {% else %}
        <h3>Register Here</h3>
        <h4>Fill out the form</h4>
        <form method="post" enctype='multipart/form-data'>
        {% csrf_token %}
        {{ user_form.as_p }}
        {{ profile_form.as_p }}
        <input type="submit" value="Register">
        </form>
        {% endif %}
    </div>
    {% endblock %}

first_project/templates/first_app/users.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    </head>
    <body>
        <div class="container">
            <h1>Please sign up here!</h1>
            <form method="POST" action="">
                {{ signup_form.as_p }}
                {% csrf_token %}
                <input type="submit" class="btn btn-primary" value="Submit">
            </form>
        </div>
        
        
        <script src="" async defer></script>
    </body>
</html>